import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import '@/styles/globals.css'

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
export const coinbaseSans = localFont({
  src: [
    {
      path: "./fonts/Coinbase-Sans/Coinbase_Sans-Regular-web-1.32.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/Coinbase-Sans/Coinbase_Sans-Bold-web-1.32.woff2",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-coinbase-sans",
});

export const coinbaseMono = localFont({
  src: [
    {
      path: "./fonts/Coinbase-Mono/Coinbase_Mono-Light-web.woff2",
      weight: "300",
      style: "normal",
    },
    {
      path: "./fonts/Coinbase-Mono/Coinbase_Mono-Regular-web.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/Coinbase-Mono/Coinbase_Mono-Medium-web.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/Coinbase-Mono/Coinbase_Mono-Bold-web.woff2",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-coinbase-mono",
});

export const burguesScript = localFont({
  src: [
    {
      path: "./fonts/burgues-script-regular.otf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-burgues-script",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${coinbaseSans.variable} ${coinbaseMono.variable} ${burguesScript.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
