export const WANT_FACTORY_ADDRESS = '0xC6c1439e3915681D4E7472839e3A3fcb5b256968' // Replace with the actual contract address

export const WANT_FACTORY_ABI = [
    {
      "type":"function",
      "name":"createWant",
      "inputs":[
        {
          "name":"_title",
          "type":"string",
          "internalType":"string"
        },
        {
          "name":"_wish",
          "type":"string",
          "internalType":"string"
        },
        {
          "name":"_successCriteria",
          "type":"string",
          "internalType":"string"
        },
        {
          "name":"_recipients",
          "type":"tuple[]",
          "internalType":"struct Want.Recipient[]",
          "components":[
            {
              "name":"addr",
              "type":"address",
              "internalType":"address"
            },
            {
              "name":"shares",
              "type":"uint8",
              "internalType":"uint8"
            }
          ]
        },
        {
          "name":"_oracle",
          "type":"address",
          "internalType":"address"
        },
        {
          "name":"_feeAddress",
          "type":"address",
          "internalType":"address"
        },
        {
          "name":"_collectFee",
          "type":"bool",
          "internalType":"bool"
        },
        {
          "name":"_categories",
          "type":"string[]",
          "internalType":"string[]"
        },
        {
          "name":"_uri",
          "type":"string",
          "internalType":"string"
        },
        {
          "name":"_initialSupportedTokens",
          "type":"address[]",
          "internalType":"contract IERC20[]"
        },
        {
          "name":"_expiryTimestamp",
          "type":"uint256",
          "internalType":"uint256"
        }
      ],
      "outputs":[
        {
          "name":"",
          "type":"address",
          "internalType":"address"
        }
      ],
      "stateMutability":"nonpayable"
    },
]