[package]
name = "wantit"
version = "0.1.0"

[dependencies]
alexandria_storage = { git = "https://github.com/keep-starknet-strange/alexandria" }
openzeppelin = { version = "0.8.1", git = "https://github.com/openzeppelin/cairo-contracts" }
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v0.17.0" }

[[target.starknet-contract]]
casm = true

[tool.snforge]
exit_first = true